name: Pull Request

on: [pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ secrets.CACHE_VERSION }}

      - name: lint
        run: npm run lint && npm run lint:prettier && npm run lint:tsc
