name: Pull Request

on: [pull_request]

jobs:
  pr:
    name: Pull Request Lint Check
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Dependencies
        run: npm install

      - name: Lint
        run: npm run lint && npm run lint:prettier && npm run lint:tsc
